name: Install Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: SetUp Python 3.7
        uses: actions/setup-python@v4
        with:
          # python version info
          python-version: '3.7'
          architecture: 'x64'
          cache: 'pip'

      - name: Print Python Version
        run: python -c "import sys; print(sys.version)"

      - name: SetUp Pip Tool
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
